remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-them
title: ddns-mlcommunity-dev
color_scheme: dark
search_enabled: true
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."